# Welcome to DATA5000 - Week 1

This week we will look into how to use Google Colab, load and work with files, and the library **pandas**

In [53]:
import sys
sys.version

'3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]'

In [54]:
import pandas as pd
pd.__version__

'2.2.2'

In [55]:
url = "https://raw.githubusercontent.com/clarkian-teachings/data5k/main/week_01/aus_cpi.csv"
df = pd.read_csv(url)

In [56]:
df.head(10) # have a look at the top 10 records

        Date   AU-CPI
0   1/1/1960  2.73973
1   1/4/1960  4.10959
2   1/7/1960  4.05405
3  1/10/1960  4.00000
4   1/1/1961  4.00000
5   1/4/1961  3.94737
6   1/7/1961  1.29870
7  1/10/1961  0.00000
8   1/1/1962  0.00000
9   1/4/1962 -1.26582

N.B. You will see some missing values (encoded as 0.00000) for some dates e.g. 1/10/1961, 1/1/1962, and many others. Data quality issues are part and parcel of business analytics, sadly.

**TODO:** Now download `aus_cpi.csv` to your local machine and then add it to your Colab session using the **Files** tool icon 📁 on the left hand ribbon and then the **Upload to session storage** button 📤

This will be important in assessments when you will have to upload your own files!

Once uploaded successfully, you would see it in files as

🄲🅂🅅 aus_cpi.csv

In [57]:
df = pd.read_csv('aus_cpi.csv')   # this will only work once the file aus_cpi.csv is uploaded successfully!

**Question:** How to look at the top 8 records ?
Type the code in the cell bellow:

In [58]:
df.head(8) # Look at the top 8 records

        Date   AU-CPI
0   1/1/1960  2.73973
1   1/4/1960  4.10959
2   1/7/1960  4.05405
3  1/10/1960  4.00000
4   1/1/1961  4.00000
5   1/4/1961  3.94737
6   1/7/1961  1.29870
7  1/10/1961  0.00000

In [59]:
df.tail(1) # Look at the bottom 1 record

         Date   AU-CPI
253  1/4/2023  6.02696

In [60]:
df.describe() # understand the distribution of the data

           AU-CPI
count  254.000000
mean     4.706993
std      3.811989
min     -1.265820
25%      2.040785
50%      3.260870
75%      7.112592
max     17.692310

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    254 non-null    object
 1   AU-CPI  254 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.1+ KB

In [62]:
df.columns # what are the columns in our dataset ?

Index(['Date', 'AU-CPI'], dtype='object')

**How to select a column ?**

In [63]:
df['AU-CPI']

0      2.73973
1      4.10959
2      4.05405
3      4.00000
4      4.00000
        ...
249    6.14478
250    7.26817
251    7.83182
252    7.02179
253    6.02696
Name: AU-CPI, Length: 254, dtype: float64

**We can construct the median of CPI-based inflation**

In [64]:
df['AU-CPI'].median() # What's the median value of CPI-based inflation ?

3.26087

In [ ]:
df.shape # Whats the shape of our data ?

(254, 2)

In [ ]:
df.dtypes # What datatypes are our columns

Date       object
AU-CPI    float64
dtype: object

**A lot of models will require the Date column to be a format of date/datetime**

Pandas provides many methods to change the datatype. In the example below we change the column Date to be a DateTime.

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    254 non-null    datetime64[ns]
 1   AU-CPI  254 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.1 KB

In [ ]:
df.dtypes

Date       object
AU-CPI    float64
dtype: object

In [ ]:
df.head(5)

        Date   AU-CPI
0   1/1/1960  2.73973
1   1/4/1960  4.10959
2   1/7/1960  4.05405
3  1/10/1960  4.00000
4   1/1/1961  4.00000

In [ ]:
df["AU-CPI"] = df["AU-CPI"].astype("int64") # Try and change the datatype of the column AU-CPI to be integer

# An integer is a whole number with no fractional part (… -2, -1, 0, 1, 2 …).
# A float (“floating-point number”) can represent numbers with a fractional part (… 1.5, 2.0, 3.14159 …)

In [ ]:
df.head() # Now double check that the change was successful

        Date  AU-CPI
0   1/1/1960       2
1   1/4/1960       4
2   1/7/1960       4
3  1/10/1960       4
4   1/1/1961       4

In [ ]:
df["AU-CPI"] = df["AU-CPI"].astype("float64") # Lastly change the datatype back to its original float type

In [ ]:
df.head() # Notice we have lost the fractional data. Be aware of this!

        Date  AU-CPI
0   1/1/1960     2.0
1   1/4/1960     4.0
2   1/7/1960     4.0
3  1/10/1960     4.0
4   1/1/1961     4.0